const RUN_STATUS = Object.freeze({
  CREATED: "CREATED",
  RUNNING: "RUNNING",
  AWAITING_APPROVAL: "AWAITING_APPROVAL",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  EXECUTING: "EXECUTING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
});

const TERMINAL_STATUSES = new Set([
  RUN_STATUS.REJECTED,
  RUN_STATUS.COMPLETED,
  RUN_STATUS.FAILED,
]);

const ALLOWED_TRANSITIONS = Object.freeze({
  [RUN_STATUS.CREATED]: new Set([RUN_STATUS.RUNNING, RUN_STATUS.FAILED]),
  [RUN_STATUS.RUNNING]: new Set([RUN_STATUS.AWAITING_APPROVAL, RUN_STATUS.FAILED]),
  [RUN_STATUS.AWAITING_APPROVAL]: new Set([RUN_STATUS.APPROVED, RUN_STATUS.REJECTED]),
  [RUN_STATUS.APPROVED]: new Set([RUN_STATUS.EXECUTING, RUN_STATUS.FAILED]),
  [RUN_STATUS.EXECUTING]: new Set([RUN_STATUS.COMPLETED, RUN_STATUS.FAILED]),
  [RUN_STATUS.REJECTED]: new Set(),
  [RUN_STATUS.COMPLETED]: new Set(),
  [RUN_STATUS.FAILED]: new Set(),
});

function assertTransition(from, to) {
  if (!ALLOWED_TRANSITIONS[from]?.has(to)) {
    throw new Error(`Invalid run transition: ${from} -> ${to}`);
  }
}

module.exports = { RUN_STATUS, TERMINAL_STATUSES, assertTransition };
